### ISSUE TITLE
Impractical assignment

### ISSUE THREAD

**Issue by wikankun** [ghazimuharam/luigi-etl-pipeline#1]
https://github.com/ghazimuharam/luigi-etl-pipeline/blob/216938cdf4ac0cfaa34fccb26dd13ca9ffd43c6d/src/luigi_preprocessed.py#L8

If you want to get "yyyymmdd" string, you can do it by `time.strftime("%Y%m%d")`.
No need to split, map, assign each of it to new variables and concate it in the end.

**Comment by ghazimuharam** [comment]
Fixed on commit [`#2931277`](https://github.com/ghazimuharam/luigi-etl-pipeline/commit/29312771fa5725d5fb694d549ac6201c0f2db3a9)
